# Is performed before the scripts in the stages step
before_script:
  - source /etc/profile

# Defines stages which are to be executed
stages:
  - build
  - test
  - publish

# Stage "build"
build:deb:
  stage: build
  image: aegir/hostmaster:packaging_base
  script:
    - export commit=$(git log -n 1 --oneline | sed 's/ .*$//')
    - export version=$(sed -ne 's/^[^(]*(\([^)]*\)).*/\1/;1p' debian/changelog)
    - export new_version="${version}+${CI_BUILD_ID}.${commit}"
    - dch -D unstable --newversion "$new_version" "automatic GitLab CI build ${CI_BUILD_ID}"
    - dpkg-buildpackage
    - mkdir build
    - mv -v ../aegir3*.deb build/

  # The files which are to be made available in GitLab as artifacts.
  artifacts:
    paths:
      - build/*


# Stage "test"
test:debian-jessie-aegir3-apt:
  stage: test
  image: debian:jessie
  dependencies:
    - build:deb
  only:
    - 7.x-3.x
    - triggers

  before_script:
    - apt-get update
    # Avoid ERROR: invoke-rc.d: policy-rc.d denied execution of start.
    - echo "#!/bin/sh" > /usr/sbin/policy-rc.d
    - echo "exit 0" >> /usr/sbin/policy-rc.d
    - apt-get install --yes sudo curl

  script: "scripts/ci-aegir-dev-install-apt-debian.sh"

test:debian-stretch-aegir3-apt:
  stage: test
  image: debian:stretch
  allow_failure: true
  dependencies:
    - build:deb
  only:
    - 7.x-3.x
    - triggers

  before_script:
    - apt-get update
    # Avoid ERROR: invoke-rc.d: policy-rc.d denied execution of start.
    - echo "#!/bin/sh" > /usr/sbin/policy-rc.d
    - echo "exit 0" >> /usr/sbin/policy-rc.d
    - apt-get install --yes sudo curl

  script: "scripts/ci-aegir-dev-install-apt-debian9.sh"

test:ubuntu-xenial-aegir3-apt:
  stage: test
  image: ubuntu:xenial
  dependencies:
    - build:deb
  only:
    - 7.x-3.x
    - triggers

  before_script:
    - apt-get update
    # Avoid ERROR: invoke-rc.d: policy-rc.d denied execution of start.
    - echo "#!/bin/sh" > /usr/sbin/policy-rc.d
    - echo "exit 0" >> /usr/sbin/policy-rc.d
    - apt-get install --yes sudo curl

  script: "scripts/ci-aegir-dev-install-apt-ubuntu.sh"


publish:unstable-repo:
  stage: publish
  dependencies:
    - build:deb
  allow_failure: true

  image: ruby:2.1
  before_script:
    # install ssh-agent
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'

    # run ssh-agent
    - eval $(ssh-agent -s)

    # add ssh key stored in SSH_PRIVATE_KEY variable to the agent store
    - ssh-add <(echo "$SSH_PRIVATE_KEY")

    - mkdir -p ~/.ssh
    - ls -la /.dockerenv
    - echo "$SSH_SERVER_HOSTKEYS" > ~/.ssh/known_hosts


  script:
    - ls -lah build/*
    - scp build/*.deb ci@aegir0.aegir.coop:/tmp/incomming
